name: Build Repo Listing

env:
  listPublishDirectory: Website
  pathToCi: ci
  
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build Release]
    types:
      - completed
  release:
    types: [published, created, edited, unpublished, deleted, released]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  
  # Build the VPM Listing Website and deploy to GitHub Pages
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      
      # Checkout Local Repository
      - name: Checkout Local Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # Checkout Automation Repository without removing prior checkouts
      - name: Checkout Automation Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          repository: NanashiTheNameless/package-list-action-custom
          path: ${{ env.pathToCi }}
          clean: false

      # Load cached data from previous runs
      - name: Restore Cache
        uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7
        with:
          path: |
            ${{ env.pathToCi }}/.nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      
      # Build Package Version Listing with Nuke
      - name: Build Package Version Listing
        run: ${{ env.pathToCi }}/build.cmd BuildRepoListing --root ${{ env.pathToCi }} --list-publish-directory $GITHUB_WORKSPACE/${{ env.listPublishDirectory }} --current-package-name ${{ vars.PACKAGE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Prepare for GitHub Pages deployment
      - name: Setup Pages
        uses: actions/configure-pages@d5606572c479bee637007364c6b4800ac4fc8573
      
      # Upload the VPM Listing Website to GitHub Pages artifacts
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: ${{ env.listPublishDirectory }}
      
      # Deploy the uploaded VPM Listing Website to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@854d7aa1b99e4509c4d1b53d69b7ba4eaf39215a